services:
  - type: web
    name: carbon-registry
    env: go
    buildCommand: go build -o bin/carbon-registry
    startCommand: ./bin/carbon-registry
    envVars:
      - key: PORT
        value: 8080
    publish:
      path: .
